services:
  database:
    image: 'postgres:17.3'
    container_name: database
    hostname: database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_EXPOSE_PORT}:5432
    volumes:
      - ${DATABASE_STORE}:/var/lib/postgresql/data
    restart: always

  java-backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG}'
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      database:
        condition: service_healthy
        restart: true
    volumes:
      - ${LOG_PATH}:/var/log
    environment:
      DOMAIN: ${DOMAIN}
      LOG_PATH: ${LOG_PATH}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_DEFAULT_SCHEMA: ${DATABASE_DEFAULT_SCHEMA}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST_PORT: ${DATABASE_HOST_PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ALLOWED_METHODS: ${ALLOWED_METHODS}
      ALLOWED_HEADERS: ${ALLOWED_HEADERS}

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: true
#  web:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#      extra_hosts:
#        - host.docker.internal:host-gateway
#    container_name: web
#    hostname: web
#    environment:
#      LOG_PATH: ${LOG_PATH}
#      DATABASE_DB: ${DATABASE_DB}
#      DATABASE_DEFAULT_SCHEMA: ${DATABASE_DEFAULT_SCHEMA}
#      DATABASE_USER: ${DATABASE_USER}
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#      DATABASE_HOST_PORT: ${DATABASE_HOST_PORT}
#      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
#      ALLOWED_METHODS: ${ALLOWED_METHODS}
#      ALLOWED_HEADERS: ${ALLOWED_HEADERS}
#    depends_on:
#      - database
#    ports:
#      - ${WEB_EXPOSE_PORT}:8080
#    extra_hosts:
#      - host.docker.internal:host-gateway
#    volumes:
#      - ${LOG_PATH}:/var/log
#    restart: always

